apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-home
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /storage/jenkins-home
  persistentVolumeReclaimPolicy: Retain
