apiVersion: apps/v1
kind: Deployment
metadata:
  name: liberty-project
spec:
  selector:
    matchLabels:
      app: liberty-project
  replicas: 3
  minReadySeconds: 120
  progressDeadlineSeconds: 600
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
      type: RollingUpdate
  template:
    metadata:
      labels:
        app: liberty-project
      annotations:
        kubernetes.io/change-cause: "Update liberty-project to 2.0.0"
    spec:
      containers:
      - name: liberty-project
        image: liberty-project:2.0.0
        ports:
        - containerPort: 9081
        readinessProbe:
          httpGet:
            path: /liberty-project/System/health
            port: 9081
          initialDelaySeconds: 10
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
